### PR TITLE
Feature main with user cfg dict

### PR DESCRIPTION
**Pull request by dyoussef**
s2p.main takes a dictionary instead of a cfg file.
Now, in s2p_test.py, we can change cfg on the fly and save time : registered_tests is now an OrderedDict and test_cfg_cluster['skip_existing'] = True in end2end_cluster
Minor modifications : mv test_{pair/triplet} in testoutput/output_{pair/triplet}

### CODE REVIEW

**Comment by dyoussef** [comment]
I will divide this PR into four parts : two PR (cfg files -> cfg dict, registered_tests as OrderedDict) and two trivial merges (removed unused testdata/config.json, mv directories)

**Comment by gfacciol** [comment]
Can you explain why we need to change dictionary to OrderedDict?

**Comment by jmichel-otb** [comment]
OrderedDict allows to get tests executed in the order they are registered. Otherwise execution order is random.
This can be useful since end2end_cluster actually needs the results from end2end_triplet. If s2p_test.py --all guarantees that end2end_triplet has been executed when running end2end_cluster, we can save testing time (use skip_existing=True when running it again for instance).

**Comment by gfacciol** [comment]
Thanks for the clarification!

**Pull request closed without merging**
