### PR TITLE
[feature] sift with percentile

### PR DESCRIPTION
**Pull request by dyoussef**
This pull request (partially) allows to deal with SIFT outliers.

### CODE REVIEW

**Review by jmichel-otb — APPROVED** [review]
This assumes that there are no more than 1% of outliers, but it is still better than min / max. Maybe add the outlier threshold has a parameter ?

**Review by carlodef — DISMISSED** [review]

**Comment by gfacciol** [comment]
That change introduces a regression in urban areas. A tile containing an isolated tall building will contain less than 1% of sift matches corresponding to this building. 
@dyoussef can you show us in which images this PR improves the results?

**Comment by jmichel-otb** [comment]
@gfacciol one could say that s2p parameters are overfitted for urban landscape ;)

In montain areas, when image quality is poor (snow patterns and shadow), there might be outlier matches that yield a very large disparity range, resulting in large processing time and memory usage, and also poor disparity map quality.

`np.percentile(100)` is equivalent to `np.max()` right ? And 0 (or 100) is not a better magic number than 1. So lets add a `sift_disparity_outlier_threshold` parameter and set it to 0 by default, and use it as `np.percentile(sift_disparity_outlier_threshold)` as min and `np.percentile(100-sift_disparity_outlier_threshold)` as max.

**Comment by jmichel-otb** [comment]
Did you find time to discuss it ? Note that with my proposal the default behaviour of s2p is preserved.

**Comment by mnhrdt** [comment]
We may have a better solution that does not break the current and correct behavior in urban regions.  Can you please send us an example input where this change improves the results?

**Comment by gfacciol** [comment]
After discussing with @mcournet @jmichel-otb, we think that instead of using a threshold based on the statistics of SIFT keyponts it would be better to derive one from the maximum height range derived from the exogenous DSM. 
This new parameter would be much easier to interpret than setting the 1% of SIFT keypoints.

**Pull request closed without merging**
