### PR TITLE
Recursive vrt

### PR DESCRIPTION
**Pull request by jmichel-otb**
gdal has difficulties reading vrt files with 10 000+ tiles. This pull request provides a recursive strategy which first builds one vrt per row, and then a global vrt of the collection of row vrt, to workaround this limitation.

Also, a vrt_to_tif option is added, in order to actually produce the output tif if wanted. In this case, if the cleaning option is activated, the source tiles are cleaned, which results in avoiding to duplicate data with the global tiff.

### CODE REVIEW

**Comment by jmichel-otb** [comment]
I am not sure what to do with this PR. From the current master, all mosaicking capabilities have been removed, and it is true that mosaicking is not necessary to run S2P. Still, it can be useful to get the global height map for instance, or global error map.

Options are 
- Do nothing and close the PR. Mosaicking is the business of S2P user.
- Modify PR to have mosaicking as a separate, utils tool. It could read the tiles.txt file and perform mosaicking of any sub-image of tiles.
- Modify PR to get back mosaicing as part of S2P pipeline. In this case, we need a dedicated global step after triangulation.

**Comment by carlodef** [comment]
I agree that it can be useful to get the global height map or a global error map, especially as vrt files. Thus I'd vote for the second option : have mosaicking as a separate utils tool.

**Review by carlodef — COMMENTED** [review]
The current state of this pull request contains commits from pull request https://github.com/MISS3D/s2p/pull/33 which has been merged already.

**Comment by gfacciol** [comment]
I agree with Carlo, the mosaicing functionality is useful.
However, if I remember well the reason why we removed it is that the
underlying "recursive" algorithm introduced an arbitrary bias on each tile.
As result the result looked nice (a 40k x 40k image is always impressive)
but it was wrong.

**Comment by jmichel-otb** [comment]
Ok, so I will write the mosaicking as a separate tool, and pay attention to @gfacciol comment on bias. Then I will submit a new PR.

**Pull request closed without merging**
