### PR TITLE
Fix fancy image

### PR DESCRIPTION
**Pull request by cpalmann**
Inside C/sift/sift_roi.c, use of gdal instead of fancy_image_fill_rectangle_float_split

### CODE REVIEW

**Comment by mnhrdt** [comment]
what is the reason for this change? does it workaround a problem in fancy_image?

**Comment by cpalmann** [comment]
Sometimes, this part of the code can load entire images in order to get small extracts (tiff not tiled).
I've made this change to avoid this. 
We had a discussion by phone this afternoon with Carlo about this change.

Moreover, using gdal instead of libtiff could allow to better handle different image formats.

**Comment by mnhrdt** [comment]
What other formats are required?

**Comment by cpalmann** [comment]
J2K for instance, or other formats used at CNES.

**Comment by mnhrdt** [comment]
Please, can you give me a list of such formats?  I would like to be able to read all of them natively (outside of s2p).

**Comment by jmichel-otb** [comment]
We discussed this with Carlo on the phone yesterday. 12 bits tiff, non-tiled tiff, jpeg2000, Erdas files (*.img), ENVI files ... all perfectly read by gdal. For now reading 12 bits tiff is impossible, reading non-tiled tiff results in loading the whole image into memory, and ready JPEG2000 is impossible. If you want to read all of them natively you will end up rewriting your own small gdal.

If this is not acceptable for you maybe we can find a way to support both gdal and your own lib and decide which to use at compile time ?

**Comment by mnhrdt** [comment]
Just to be clear, I agree 100% with this pull request.  

I was asking out of curiosity, because I have a personal interest in image formats and input/output.  In fact, writing a small "gdal" is precisely my goal (but independent of all the geographic stuff, I want to deal with pure images in an arbitrary context).  Tiffs with 12 bits sound cool!

**Comment by jmichel-otb** [comment]
Ok but I can understand that for some reason (being able to distribute a reference implementation along with a paper), you would like to keep dependencies minimal. That is why I suggested to be able to choose at compile time.

**Comment by carlodef** [comment]
Anyway it would not require much work to restore an optional fancy_image i/o variant. It could be done later if for some reason we don't want the gdal dependency to be mandatory. For the moment let's use gdal and see what happens.

**Comment by cpalmann** [comment]
Hi Carlo,

the gdal api claims that "This method will automatically take care of data type conversion, up/down sampling and **windowing**", but apparently, I made a mistake with the meaning of "windowing".

What about clipping the ROI manually ?

```
// read the roi in the input image
GDALDatasetH  hDataset;
GDALAllRegister();
hDataset = GDALOpen( v[1], GA_ReadOnly );
if( hDataset == NULL )
{
    fprintf(stderr, "ERROR : can't open %s\n", v[1]);
}

//Clipping
int sizeX = GDALGetRasterXSize( hDataset );
int sizeY = GDALGetRasterYSize( hDataset );
if (x<0) x=0;
if (y<0) y=0;
if (!(x+w < sizeX))
    w=sizeX-x-1;
if (!(y+h < sizeY))
    h=sizeY-y-1;

GDALRasterBandH hBand;
hBand = GDALGetRasterBand( hDataset, 1 );
float *roi;
roi = (float *) CPLMalloc(sizeof(float)*w*h);
GDALRasterIO( hBand, GF_Read, x, y, w, h, 
          roi, w, h, GDT_Float32, 
          0, 0 );
GDALClose(hBand);
GDALClose(hDataset);
```

Sorry not to make a proper pull request, but today I meet some obstacles in connecting my local repo to the internet...

**Comment by carlodef** [comment]
It's done, thank you!

**Pull request merged**
