### PR TITLE
[bugfix] Fix relative paths inconsistencies

### PR DESCRIPTION
**Pull request by jmichel-otb**
This PR tries to solve the following issue: when relative path is used as out_dir, the config files written in out_dir can only be used from the same cwd as the first s2p that generated the output dir.

As a result, the following will fail:

$ s2p.py config.json
$ cd somewhere-else
$ s2p.py path_to_output_dir/config.json

One solution would be to make all paths absolute in the config.json exported in output directory, but then we will loose the ability to move the output folder and still be able to use it.

This PR proposes the following solution:
1) If a relative path is used for out_dir in config.json, then s2p.py interprets it as relative to the config.json path, and not the cwd. If out_dir is absolute, it is left unchanged.

2) config.json exported in output dir always contains relative path : $out_dir/config.json has "." as out_dir and $out_dir/row_*/col_*/config.json has "../.." as outdir. One can therefore move the outdir and still get a working config.json.

3) All input data path are made absolute at config.json loading, and $out_dir/config.json therefore contains absolute path for all input data.

A side effect is that to allow for 1) we need to load the config.json through a dedicated helper function, and not through json.load(). This is because we need the path to the json file to update the out_dir in the dictionnary.

This is only a proposal on how to fix it, and comments or alternative solutions are welcome.

### CODE REVIEW

**Review by dyoussef — APPROVED** [review]

**Comment by gfacciol** [comment]
I don't understand this issue/fix. Can someone explain it to me?
Why config.json should contain the path of the output directory?

config.json is ment to be inside the directory where the output is.

The only exception to this is when we call s2p from the command line, in
which case we have to specify the output directory AND s2p copies
config.json inside this directory.

I'm surely missing something here.
Thanks in advance!

**Comment by jmichel-otb** [comment]
Hi Gabriele, I think we agree on the expected behaviour, but the current
behaviour is not the one you describe : copied config.json always contain
output_dir (a simple copy of it). You can run one of the tests in master to
check that.

This PR ensure that you can run the config.json exported in output_dir from
everywhere and always generate results in that output dir.

I can provide detailed use cases later if needed (but right now on my phone
it would be a bit tedious).

**Comment by jmichel-otb** [comment]
Here is the use case to understand the issue and how it is fixed by the PR. 

Starting from today's master, move to s2p source folder (I will refer to $S2P)
$ cd $S2P

Run s2p.py on the pair test case
$ ./s2p.py 

Go to result folder 
$ cd testoutput/output_pair/

Try to run the exported config.json
$ ../../s2p.py config.json

Pb 1) This will fail because current working directory (CWD) is $S2P/testoutput/output_pair and input data in the json file are as "img": "testdata/input_pair/img_01.tif", a relative path that does not exists wrt CWD. 

(With my PR, those "img" path would have been made absolute before exporting, so this would have worked instead of failing)

Pb 2) Now, suppose it is not failing (because you fixed the paths or because this part of the PR has been accepted and merged). Then running 
$ ../../s2p.py config.json

Will result in creating $S2P/testoutput/output_pair/testoutput/output_pair/ because out_dir in config.json is testoutput/output_pair/ and this is relative to CWD, which is $S2P/testoutput/output_pair/.

(With my PR, out_dir="." in this config.json, so running $ ../../s2p.py config.json from anywhere will result in re-generating output data in $S2P/testoutput/output_pair/ )

Pb 3) Now move to tiles_row_150_height_350/col_150_width_350/ and run the json file
$ cd tiles_row_150_height_350/col_150_width_350/
$ ../../../../s2p.py config.json

This will result in creating  $S2P/testoutput/output_pair/tiles_row_150_height_350/col_150_width_350/testoutput/output_pair/ because config.json is testoutput/output_pair/ and this is relative to CWD, which is $S2P/testoutput/output_pair/tiles_row_150_height_350/col_150_width_350/.

(With my PR in tiles_row_150_height_350/col_150_width_350/config.json, out_dir='../..' so that running it from anywhere will results in re-generating output data in tiles_row_150_height_350/col_150_width_350/)

**Comment by jmichel-otb** [comment]
We could achieve the same behavior by making out_dir optional in config.json and using the config.json location as outdir (with some tricks for tiles folder), but this is more code changes and less obvious.

**Comment by jmichel-otb** [comment]
Last comment : looking at my comments, I think my PR is missing one thing, which is make relative input data path relative to config.json and not CWD. This would be more consistent with what is done for output_dir, and it would also save the pain of writing portable json files (you could have your json files next to your data and move them altogether).

**Comment by jmichel-otb** [comment]
Keeping up with master with all those submodule PR merged is quite heavy. Can someone give his opinion on this topic ? I provided detailed use cases so we can start discussing it.

Sidenote, I think that travis is doing some on-the-fly merge with master when testing a PR branch.

**Pull request merged**
