### PR TITLE
[feature] plyflatten gdal

### PR DESCRIPTION
**Pull request by dyoussef**
used gdal for writing dsm

### CODE REVIEW

**Review by jmichel-otb — APPROVED** [review]

**Comment by carlodef** [comment]
Hi David, I understand that the goal of this contribution is to write geotif metadata using GDAL instead of libgeotif. Is there a use case where libgeotif doesn't work? I feel that the GDAL version is much longer  and hard to read than the libgeotif version.

**Comment by dyoussef** [comment]
Hi Carlo, I made this pull request to avoid this #83

**Comment by jmichel-otb** [comment]
IMHO, all reading and writing should go through Gdal. The reason is that someone already did the work of finding the optimal use of libtiff/libggeotiff, so there is no reason to do this over and over. I agree that the code looks more complex, but maybe David can  restore the set_geotiff_header method and move all gdal metadata related stuff there. This would make main body more compact and easy to read.

**Review by mnhrdt — APPROVED** [review]
That's it.  Now plyflatten uses GDAL to save the dsm.

The only change with respect to dyoussef's version is that the gdal code is put on a separate function, instead of calling it directly from main.

RANT: In reply of Julien Michel suggestion that GDAL should be used for all the i/o, I disagree strongly for the following reasons.

1. the code should be modular, and all these C utils are used outside s2p and outside the geographic context, where gdal does not make sense (e.g., microscopy, astronomy, photography, medical images).

2. the gdal API is the stuff of nightmares.  The code for writing an image in gdal is much more complicated than in any other particular image library.  I just do not see the point of using gdal only for input/output.  The "A" in the GDAL acronym is ironic, I suppose?

3. I will be back!  further revisions of this code will make GDAL optional (but enabled by default).

**Comment by jmichel-otb** [comment]
Hi Enric,

Thanks for those patches ;)

1) makes sense. In the frame of S2P we read mostly satellite images, so GDAL seemed a good fit, hence my suggestion.

2) A stands for abstraction and it works. You do not see the point because you mostly manipulated jp2 and tiff, but gdal knows how to read/write a really impressive list of image file formats under a single API, including metadata. Yes gdal API is quite complex, and but it is also really powerful (see for instance all that can be done with VRT : http://gdal.org/gdal_vrttut.html ). 

Anyway I am ok with 3), lets make it optional and everyone will be happy.

**Pull request merged**
