### PR TITLE
[bugfix] fix matching interface

### PR DESCRIPTION
**Pull request by dyoussef**
- expose sift_thresh parameter for matching
- remove method parameter (deprecated)

### CODE REVIEW

**Comment by gfacciol** [comment]
@dyoussef please expose the "method" parameter in matching.c which is implemented in the underlying library

**Comment by carlodef** [comment]
(the underlying library is the file `c/sift/sift_anatomy_20141201/lib_matching.c`)

**Comment by dyoussef** [comment]
> 
> 
> @dyoussef please expose the "method" parameter in matching.c which is implemented in the underlying library
> 
> 
> (the underlying library is the file `c/sift/sift_anatomy_20141201/lib_matching.c`)


Done

**Comment by gfacciol** [comment]
Thanks @dyoussef, this is great!

**Pull request merged**
