### PR TITLE
[feature] mosaic

### PR DESCRIPTION
**Pull request by jmichel-otb**
This PR brings the ability to mosaic any sub-images from the tiles folder, such as height_map.tif or rpc_error.tif for instance.

It is written as a completely separated tool (s2p_mosaic.py), and has no impact on s2p.py or s2plib.

A new test has been added for the tool in s2p_test.py.

The use is as follows: 
usage: s2p_mosaic.py [-h] tiles.txt out.tif|out.vrt pair_1/height_map.tif

S2P: mosaic tool

positional arguments:
  tiles.txt             path to the tiles.txt file
  out.tif|out.vrt       path to the the output file
  pair_1/height_map.tif
                        path to the sub-image to mosaic. Can be (but not
                        limited to) height_map.tif, pair_n/height_map.tif,
                        pair_n/rpc_err.tif, cloud_water_image_domain_mask.png.
                        Note that rectified_* files CAN NOT be used.

First argument is the tiles.txt file produced by s2p.py initialisation step in the output directory.

Second argument is the path to the output image. If vrt extension is used, the tool will only generate vrt files (using recursive scheme). If tif extension is used, the tool will gdal_translate the final vrt to tif and remove all intermediate vrt. No other extensions are supported.

Third argument is the relative path of the sub-image to mosaic inside the tile folder. Any tile sub-image can be used as long as they match the tile size.

### CODE REVIEW

**Review by dyoussef — APPROVED** [review]

**Comment by jmichel-otb** [comment]
Keeping up with master is heavy. Can someone give his opinion on this ? It does not impact s2p.py or s2plib/ so it is rather safe to approve it.

**Comment by mnhrdt** [comment]
The program seems useful.  I see no problem with admitting it, but I have a few questions : 
1. shouldn't it go into "bin" with the other executables?
2. can you provide some context on why this program is needed?
3. the usage message is very confusing, the "|" is not a pipe! It took a lot of eye-crossing to understand...
4. (minor) the format of the text file: lines longer than 80 chars, lots of tailing whitespace, etc.

**Comment by jmichel-otb** [comment]
Context : during S2P process there are a lot of intermediate products that are computed at the tile level. height_map.tif is the most obvious one, but I think there will be other in the future (for instance 2D disparity maps, triangluation error maps ...). It is often very useful to be able to analyse those intermediate products at the whole whole reference image scale, which is the purpose of this tool.

Note : gdalbuildvrt will not do the job because those intermediate products are not georeferenced.

**Comment by jmichel-otb** [comment]
Regarding moving to bin/ : I agree that this tool should not be in root directory. My definition of bin/ is a folder that only contains compiled code that you can throw away and rebuild, so the tool does not really fit in. Maybe we could add a utils folder ?

**Comment by jmichel-otb** [comment]
I will push patches to adress other comments tomorrow.

**Comment by jmichel-otb** [comment]
All remaining comments addressed in new commits.

**Review by dyoussef — APPROVED** [review]

**Review by carlodef — APPROVED** [review]

**Pull request merged**
